import { useState, useMemo, useCallback, useRef, useEffect } from "react";
import * as Papa from "papaparse";
import * as XLSX from "xlsx";
import { Trash2, Upload, Download, Search, Package, Database, Copy, Filter } from "lucide-react";

const C = { bg:"#0f0f1a", bg2:"#161625", bg3:"#1c1c30", bg4:"#222238", border:"#2a2a3e", text:"#e8e8f0", text2:"#8888aa", text3:"#6b6b8a", blue:"#3b82f6", purple:"#8b5cf6", green:"#10b981", yellow:"#f59e0b", pink:"#ec4899", red:"#ef4444", white:"#fff", orange:"#f97316", dark:"#0a0a14", rowAlt:"#1a1a30", sidebar:"#111120", sideHover:"#1a1a35", sideActive:"#1e2a4a", cyan:"#06b6d4" };
function findCol(h,a){const l=h.map(x=>x.toLowerCase().replace(/[\s_]/g,""));for(const x of a){const la=x.toLowerCase().replace(/[\s_]/g,"");const i=l.indexOf(la);if(i>=0)return h[i];}for(const x of a){const la=x.toLowerCase().replace(/[\s_]/g,"");for(let i=0;i<l.length;i++)if(l[i].includes(la))return h[i];}return null;}

const Card=({title,value,sub,color=C.blue,icon})=>(<div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"18px 22px",flex:1,minWidth:140}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{color:C.text2,fontSize:10,fontWeight:700,textTransform:"uppercase",letterSpacing:1.2}}>{title}</span>{icon&&<span style={{fontSize:16}}>{icon}</span>}</div><div style={{color,fontSize:30,fontWeight:800,marginTop:6,lineHeight:1}}>{value}</div>{sub&&<div style={{color:C.text3,fontSize:11,marginTop:4}}>{sub}</div>}</div>);
const Btn=({children,bg=C.blue,onClick,disabled,small,icon:Icon,style:s2})=>(<button onClick={onClick} disabled={disabled} style={{background:disabled?"#333":bg,color:C.white,border:"none",borderRadius:6,padding:small?"5px 12px":"8px 18px",fontWeight:700,fontSize:small?11:12,cursor:disabled?"default":"pointer",opacity:disabled?0.5:1,display:"inline-flex",alignItems:"center",gap:6,transition:"all 0.15s",...s2}}>{Icon&&<Icon size={small?13:15}/>}{children}</button>);
const SH=({icon:Icon,title,sub})=>(<div style={{marginBottom:14}}><div style={{display:"flex",alignItems:"center",gap:8}}>{Icon&&<Icon size={20} color={C.blue}/>}<span style={{color:C.text,fontSize:18,fontWeight:800}}>{title}</span></div>{sub&&<div style={{color:C.text3,fontSize:12,marginTop:2,marginLeft:28}}>{sub}</div>}</div>);
const Badge=({children,bg,color=C.white})=>(<span style={{background:bg,color,fontSize:10,fontWeight:700,padding:"3px 8px",borderRadius:4,whiteSpace:"nowrap"}}>{children}</span>);

export default function App(){
  const [skuClients,setSkuClients]=useState(()=>{try{const v=window._skuClients;return v?JSON.parse(v):{};}catch(e){return{};}});
  const [skuActive,setSkuActive]=useState("");const [skuNewName,setSkuNewName]=useState("");const [skuInwards,setSkuInwards]=useState([]);const [skuPaste,setSkuPaste]=useState("");const [skuFilter,setSkuFilter]=useState("all");const [skuSearch,setSkuSearch]=useState("");const skuMRef=useRef();const skuIRef=useRef();
  const saveSku=(d)=>{setSkuClients(d);try{window._skuClients=JSON.stringify(d);}catch(e){}};

  const handleSkuMaster=useCallback((e)=>{const file=e.target.files[0];if(!file)return;const cn=skuNewName.trim()||skuActive||file.name.replace(/\.[^.]+$/,"");const ext=file.name.split(".").pop().toLowerCase();
    const proc=(rows,hds)=>{const sc=findCol(hds,["SKU","sku","Item Code","ItemCode","Material","Product Code","Barcode","Article"]),dc=findCol(hds,["ItemDescription","Item Description","Description","Product Name","Name"]),uc=findCol(hds,["InvUOM","UOM","Unit"]),upc=findCol(hds,["UPC","EAN","Barcode","GTIN"]),tb=findCol(hds,["Trackbys","TrackBy","Track By"]),tr=findCol(hds,["TrackbyReq","TrackBy Required","Track By Required"]),d2=findCol(hds,["Description2","Description 2","Desc2"]),du=findCol(hds,["DIMUOM","Dim UOM"]),un=findCol(hds,["NumofInvUnits","Units Per"]),wt=findCol(hds,["WeightKgs","Weight"]);
      const mr=rows.map(r=>{const s=String(r[sc]||"").trim();if(!s)return null;return{sku:s,desc:dc?String(r[dc]||"").trim():"",uom:uc?String(r[uc]||"").trim():"",upc:upc?String(r[upc]||"").trim():"",trackby:tb?String(r[tb]||"").trim():"",trackbyReq:tr?String(r[tr]||"").trim():"",desc2:d2?String(r[d2]||"").trim():"",dimUom:du?String(r[du]||"").trim():"",units:un?r[un]:"",weight:wt?r[wt]:""};}).filter(Boolean);
      const up={...skuClients,[cn]:{skus:mr,fileName:file.name,loadedAt:new Date().toISOString(),count:mr.length}};saveSku(up);setSkuActive(cn);setSkuNewName("");};
    if(ext==="csv"){Papa.parse(file,{header:true,skipEmptyLines:true,complete:(r)=>{proc(r.data,r.meta.fields||[]);}});}
    else{const rd=new FileReader();rd.onload=(ev)=>{const wb=XLSX.read(ev.target.result,{type:"array"});let sn=wb.SheetNames[0];for(const s of wb.SheetNames){const l=s.toLowerCase();if(l.includes("master")||l.includes("sku")||l.includes("client"))sn=s;}const json=XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:""});proc(json,json.length?Object.keys(json[0]):[]);};rd.readAsArrayBuffer(file);}e.target.value="";},[skuClients,skuActive,skuNewName]);

  const runCheck=(list)=>{const cl=skuClients[skuActive];if(!cl)return;const mm={};cl.skus.forEach(m=>{mm[m.sku.toUpperCase().trim()]=m;});
    setSkuInwards(list.map((s,i)=>{const mt=mm[s.toUpperCase().trim()];return{id:i,sku:s,status:mt?"On Master":"Needs Creating",desc:mt?.desc||"",uom:mt?.uom||"",upc:mt?.upc||"",trackby:mt?.trackby||"",trackbyReq:mt?.trackbyReq||"Not found",desc2:mt?.desc2||""};}));};

  const handleSkuInFile=useCallback((e)=>{const file=e.target.files[0];if(!file)return;const ext=file.name.split(".").pop().toLowerCase();
    const proc=(rows,hds)=>{const sc=findCol(hds,["SKU","sku","Item Code","ItemCode","Material","Product Code","Barcode","Article"])||hds[0];runCheck(rows.map(r=>String(r[sc]||"").trim()).filter(Boolean));};
    if(ext==="csv"){Papa.parse(file,{header:true,skipEmptyLines:true,complete:(r)=>{proc(r.data,r.meta.fields||[]);}});}
    else{const rd=new FileReader();rd.onload=(ev)=>{const wb=XLSX.read(ev.target.result,{type:"array"});const json=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});proc(json,json.length?Object.keys(json[0]):[]);};rd.readAsArrayBuffer(file);}e.target.value="";},[skuClients,skuActive]);

  const skuStats=useMemo(()=>{const t=skuInwards.length,on=skuInwards.filter(r=>r.status==="On Master").length;return{total:t,onMaster:on,nc:t-on};},[skuInwards]);
  const filtSku=useMemo(()=>skuFilter==="needs_creating"?skuInwards.filter(r=>r.status==="Needs Creating"):skuFilter==="on_master"?skuInwards.filter(r=>r.status==="On Master"):skuInwards,[skuInwards,skuFilter]);
  const masterSearch=useMemo(()=>{if(!skuSearch||!skuClients[skuActive])return[];const q=skuSearch.toLowerCase();return skuClients[skuActive].skus.filter(m=>m.sku.toLowerCase().includes(q)||m.desc.toLowerCase().includes(q)||m.upc.toLowerCase().includes(q)).slice(0,50);},[skuSearch,skuActive,skuClients]);
  const exportSku=()=>{if(!skuInwards.length)return;const ws=XLSX.utils.json_to_sheet(skuInwards.map(r=>({SKU:r.sku,Status:r.status,Description:r.desc,UOM:r.uom,UPC:r.upc,TrackBy:r.trackby,TrackByRequired:r.trackbyReq})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"SKU Check");const nc=skuInwards.filter(r=>r.status==="Needs Creating");if(nc.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(nc.map(r=>({SKU:r.sku}))),"Needs Creating");XLSX.writeFile(wb,`SKU_Check_${skuActive}_${new Date().toISOString().slice(0,10)}.xlsx`);};

  const [winW,setWinW]=useState(typeof window!=="undefined"?window.innerWidth:1920);
  useEffect(()=>{const h=()=>setWinW(window.innerWidth);window.addEventListener("resize",h);return()=>window.removeEventListener("resize",h);},[]);
  const isC=winW<1024,isW=winW>=1920,isU=winW>=2400;const cp=isU?32:isW?24:isC?12:20;const mx=isU?1800:isW?1500:9999;const sf=isU?1.15:isW?1.05:1;

  const cns=Object.keys(skuClients);const ad=skuClients[skuActive];const hr=skuInwards.length>0;

  return(<div style={{background:C.bg,minHeight:"100vh",color:C.text,fontFamily:"'Segoe UI',system-ui,-apple-system,sans-serif",fontSize:Math.round(14*sf),display:"flex",justifyContent:"center"}}>
    <div style={{width:"100%",maxWidth:mx,padding:cp}}>
      <SH icon={Package} title="SKU Checker" sub="Check inwards SKUs against client master lists"/>
      <div style={{display:"grid",gridTemplateColumns:isC?"1fr":"1fr 1fr",gap:10,marginBottom:12}}>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}>
          <div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Client Master Profiles</div>
          {cns.length>0&&<div style={{display:"flex",gap:4,flexWrap:"wrap",marginBottom:10}}>{cns.map(n=>{const d=skuClients[n],ia=n===skuActive;return(<div key={n} onClick={()=>setSkuActive(n)} style={{background:ia?C.sideActive:C.bg2,border:`1px solid ${ia?C.cyan:C.border}`,borderRadius:8,padding:"10px 14px",cursor:"pointer",flex:"1 1 auto",minWidth:140}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{color:ia?C.cyan:C.text,fontSize:12,fontWeight:700}}>{n}</span><Trash2 size={12} color={C.red} style={{cursor:"pointer",opacity:0.6}} onClick={(e)=>{e.stopPropagation();if(confirm(`Delete ${n}?`)){const u={...skuClients};delete u[n];saveSku(u);if(skuActive===n)setSkuActive("");}}}/></div>
            <div style={{color:C.text3,fontSize:10,marginTop:4}}>{d.count.toLocaleString()} SKUs · {d.fileName}</div></div>);})}</div>}
          <div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}><input value={skuNewName} onChange={e=>setSkuNewName(e.target.value)} placeholder="New client name..." style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"7px 10px",fontSize:12,flex:1,minWidth:140}}/>
            <Btn small bg={C.cyan} onClick={()=>skuMRef.current?.click()} icon={Upload}>Upload Master</Btn><input ref={skuMRef} type="file" accept=".xlsx,.xls,.csv" onChange={handleSkuMaster} style={{display:"none"}}/></div>
          <div style={{color:C.text3,fontSize:10,marginTop:6}}>Upload client master SKU file (.xlsx / .csv)</div></div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}>
          <div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>{ad?`Active: ${skuActive}`:"No Client Selected"}</div>
          {ad?<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginBottom:10}}>
            <div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:C.cyan,fontSize:22,fontWeight:800}}>{ad.count.toLocaleString()}</div><div style={{color:C.text3,fontSize:9}}>Master SKUs</div></div>
            <div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:C.green,fontSize:22,fontWeight:800}}>{skuStats.onMaster}</div><div style={{color:C.text3,fontSize:9}}>On Master</div></div>
            <div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:skuStats.nc?C.red:C.text3,fontSize:22,fontWeight:800}}>{skuStats.nc}</div><div style={{color:C.text3,fontSize:9}}>Needs Creating</div></div></div>
            <div style={{color:C.text3,fontSize:10}}>Source: {ad.fileName}</div></>
          :<div style={{color:C.text3,fontSize:12,padding:"20px 0"}}>Select or upload a client master</div>}</div></div>

      {ad&&<div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px",marginBottom:12}}>
        <div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Check Inwards SKUs</div>
        <div style={{display:"flex",gap:8,alignItems:"flex-start",flexWrap:"wrap"}}>
          <div style={{flex:1,minWidth:250}}>
            <textarea value={skuPaste} onChange={e=>setSkuPaste(e.target.value)} placeholder="Paste SKUs (one per line, comma, or semicolon separated)..." style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"10px 12px",fontSize:12,fontFamily:"monospace",width:"100%",height:80,resize:"vertical",outline:"none"}}/>
            <div style={{display:"flex",gap:6,marginTop:6}}>
              <Btn small bg={C.cyan} onClick={()=>{const l=skuPaste.split(/[\n,;]+/).map(s=>s.trim()).filter(Boolean);if(l.length)runCheck(l);setSkuPaste("");}} disabled={!skuPaste.trim()} icon={Search}>Check</Btn>
              <Btn small bg="#e94560" onClick={()=>skuIRef.current?.click()} icon={Upload}>Upload</Btn><input ref={skuIRef} type="file" accept=".xlsx,.xls,.csv" onChange={handleSkuInFile} style={{display:"none"}}/>
              {hr&&<Btn small bg={C.green} onClick={exportSku} icon={Download}>Export</Btn>}{hr&&<Btn small bg="#2a2a3e" onClick={()=>setSkuInwards([])}>Clear</Btn>}</div></div>
          <div style={{minWidth:200}}><div style={{color:C.text3,fontSize:10,marginBottom:6}}>Search Master</div>
            <input value={skuSearch} onChange={e=>setSkuSearch(e.target.value)} placeholder="SKU, desc, UPC..." style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"7px 10px",fontSize:12,width:"100%"}}/></div></div></div>}

      {skuSearch&&masterSearch.length>0&&<div style={{background:C.bg3,border:`1px solid ${C.cyan}44`,borderRadius:10,padding:"12px 16px",marginBottom:12}}>
        <div style={{color:C.cyan,fontSize:11,fontWeight:700,marginBottom:8}}>Master: {masterSearch.length} results</div>
        <div style={{overflow:"auto",maxHeight:250}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr>{["SKU","Description","UOM","UPC","TrackBy","TrackBy Req"].map((h,i)=>(<th key={i} style={{background:C.bg2,color:C.text2,padding:"8px 10px",textAlign:"left",fontWeight:700,fontSize:10,borderBottom:`1px solid ${C.border}`,position:"sticky",top:0}}>{h}</th>))}</tr></thead>
          <tbody>{masterSearch.map((m,i)=>(<tr key={i} style={{background:i%2?C.rowAlt:C.bg3}}><td style={{padding:"6px 10px",color:C.cyan,fontFamily:"monospace",fontWeight:700,fontSize:11}}>{m.sku}</td><td style={{padding:"6px 10px",color:C.text,maxWidth:250,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{m.desc}</td><td style={{padding:"6px 10px",color:C.text2}}>{m.uom}</td><td style={{padding:"6px 10px",color:C.text3,fontFamily:"monospace",fontSize:10}}>{m.upc}</td><td style={{padding:"6px 10px",color:C.yellow,fontSize:10}}>{m.trackby}</td><td style={{padding:"6px 10px",color:C.orange,fontSize:10}}>{m.trackbyReq}</td></tr>))}</tbody></table></div></div>}

      {hr&&<><div style={{display:"flex",gap:8,marginBottom:12,flexWrap:"wrap"}}><Card title="Checked" value={skuStats.total} color={C.blue} icon="📋"/><Card title="On Master" value={skuStats.onMaster} sub={skuStats.total?`${(skuStats.onMaster/skuStats.total*100).toFixed(1)}%`:""} color={C.green} icon="✅"/><Card title="Needs Creating" value={skuStats.nc} sub={skuStats.nc?"action required":"all clear!"} color={skuStats.nc?C.red:C.green} icon={skuStats.nc?"⚠️":"✅"}/></div>
        <div style={{display:"flex",gap:6,marginBottom:10,alignItems:"center"}}><Filter size={14} color={C.text3}/>{[["all","All",C.blue],["on_master","On Master",C.green],["needs_creating","Needs Creating",C.red]].map(([v,l,cl])=>(<button key={v} onClick={()=>setSkuFilter(v)} style={{background:skuFilter===v?cl+"22":"transparent",color:skuFilter===v?cl:C.text3,border:`1px solid ${skuFilter===v?cl:C.border}`,borderRadius:6,padding:"5px 12px",fontSize:11,fontWeight:700,cursor:"pointer"}}>{l} ({v==="all"?skuStats.total:v==="on_master"?skuStats.onMaster:skuStats.nc})</button>))}</div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,overflow:"auto",maxHeight:500}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr>{["SKU","Status","Description","UOM","UPC","TrackBy Required","Desc2"].map((h,i)=>(<th key={i} style={{background:C.bg2,color:C.text2,padding:"10px 12px",textAlign:"left",fontWeight:700,fontSize:10,borderBottom:`1px solid ${C.border}`,whiteSpace:"nowrap",position:"sticky",top:0,zIndex:1}}>{h}</th>))}</tr></thead>
          <tbody>{filtSku.map((r,ri)=>{const on=r.status==="On Master";return(<tr key={r.id} style={{background:ri%2?C.rowAlt:C.bg3,borderLeft:`3px solid ${on?C.green:C.red}`}}><td style={{padding:"8px 12px",color:C.text,fontFamily:"monospace",fontWeight:700,fontSize:12}}>{r.sku}</td><td style={{padding:"8px 12px"}}><Badge bg={on?C.green+"22":C.red+"22"} color={on?C.green:C.red}>{r.status}</Badge></td><td style={{padding:"8px 12px",color:C.text,maxWidth:220,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{r.desc||"—"}</td><td style={{padding:"8px 12px",color:C.text2}}>{r.uom||"—"}</td><td style={{padding:"8px 12px",color:C.text3,fontFamily:"monospace",fontSize:10}}>{r.upc||"—"}</td><td style={{padding:"8px 12px",color:on?(r.trackbyReq.includes("Lot")?C.yellow:r.trackbyReq.includes("Not")?C.red:C.text2):C.red,fontSize:10,fontWeight:600}}>{r.trackbyReq||"—"}</td><td style={{padding:"8px 12px",color:C.text3,maxWidth:200,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",fontSize:10}}>{r.desc2||"—"}</td></tr>);})}</tbody></table></div>
        {skuStats.nc>0&&<div style={{background:C.bg3,border:`1px solid ${C.red}44`,borderRadius:10,padding:"14px 18px",marginTop:12}}>
          <div style={{color:C.red,fontSize:12,fontWeight:700,marginBottom:8}}>⚠️ {skuStats.nc} SKU{skuStats.nc>1?"s":""} need creating</div>
          <div style={{display:"flex",flexWrap:"wrap",gap:4}}>{skuInwards.filter(r=>r.status==="Needs Creating").map(r=>(<span key={r.id} style={{background:C.red+"18",color:C.red,fontSize:11,fontFamily:"monospace",fontWeight:600,padding:"3px 8px",borderRadius:4,border:`1px solid ${C.red}33`}}>{r.sku}</span>))}</div>
          <Btn small bg={C.red} onClick={()=>{navigator.clipboard?.writeText(skuInwards.filter(r=>r.status==="Needs Creating").map(r=>r.sku).join("\n"));}} icon={Copy} style={{marginTop:10}}>Copy to Clipboard</Btn></div>}</>}

      {!ad&&!cns.length&&<div style={{textAlign:"center",padding:50,color:C.text3}}><Database size={40} color={C.text3} style={{opacity:0.2,marginBottom:12}}/><div style={{fontSize:15,color:C.text2,marginBottom:6}}>How it works</div>
        <div style={{fontSize:12,lineHeight:1.8,maxWidth:520,margin:"0 auto",textAlign:"left"}}><span style={{color:C.cyan,fontWeight:700}}>1.</span> Upload a <strong style={{color:C.text}}>Client Master SKU</strong> file from your WMS<br/><span style={{color:C.cyan,fontWeight:700}}>2.</span> Stored as a <strong style={{color:C.text}}>client profile</strong> — add multiple clients<br/><span style={{color:C.cyan,fontWeight:700}}>3.</span> Paste or upload incoming SKUs<br/><span style={{color:C.cyan,fontWeight:700}}>4.</span> See <span style={{color:C.green,fontWeight:700}}>On Master</span> vs <span style={{color:C.red,fontWeight:700}}>Needs Creating</span><br/><span style={{color:C.cyan,fontWeight:700}}>5.</span> See <span style={{color:C.yellow}}>tracking requirements</span> (Lot#, Expiry, SN)<br/><span style={{color:C.cyan,fontWeight:700}}>6.</span> Export or copy "Needs Creating" list</div></div>}
    </div>
  </div>);
}
