import { useState, useMemo, useCallback, useRef, useEffect } from "react";
import * as Papa from "papaparse";
import * as XLSX from "xlsx";
import { ChevronRight, RefreshCw, Home, Menu, X, Save, Trash2, Upload, Download, Eye, EyeOff, Mail, Search, Package, Database, Copy, Filter } from "lucide-react";

const YEAR = 2026;
const C = { bg:"#0f0f1a", bg2:"#161625", bg3:"#1c1c30", bg4:"#222238", border:"#2a2a3e", text:"#e8e8f0", text2:"#8888aa", text3:"#6b6b8a", blue:"#3b82f6", purple:"#8b5cf6", green:"#10b981", yellow:"#f59e0b", pink:"#ec4899", red:"#ef4444", white:"#fff", orange:"#f97316", dark:"#0a0a14", rowAlt:"#1a1a30", sidebar:"#111120", sideHover:"#1a1a35", sideActive:"#1e2a4a", cyan:"#06b6d4" };
const pad=n=>String(n).padStart(2,"0");
function findCol(h,a){const l=h.map(x=>x.toLowerCase().replace(/[\s_]/g,""));for(const x of a){const la=x.toLowerCase().replace(/[\s_]/g,"");const i=l.indexOf(la);if(i>=0)return h[i];}for(const x of a){const la=x.toLowerCase().replace(/[\s_]/g,"");for(let i=0;i<l.length;i++)if(l[i].includes(la))return h[i];}return null;}

function parseMSG(buf){
  try{
    const cfb=XLSX.CFB.read(buf,{type:"array"});
    const getStr=(pid)=>{for(const tp of["001F","001E"]){const nm="/__substg1.0_"+pid+tp;const e=XLSX.CFB.find(cfb,nm);if(e&&e.content&&e.content.length){
      if(tp==="001F"){let s="";const b=e.content;for(let i=0;i<b.length-1;i+=2)s+=String.fromCharCode(b[i]|(b[i+1]<<8));return s.replace(/\0+$/,"");}
      else{let s="";const b=e.content;for(let i=0;i<b.length;i++)s+=String.fromCharCode(b[i]);return s.replace(/\0+$/,"");}}}return"";};
    const subject=getStr("0037"),senderName=getStr("0C1A"),senderEmail=getStr("0C1F")||getStr("0065")||getStr("5D01"),body=getStr("1000");
    let date="";
    const pe=XLSX.CFB.find(cfb,"/__properties_version1.0");
    if(pe&&pe.content){const b=pe.content;const hs=32;
      for(let o=hs;o+16<=b.length;o+=16){const pt=b[o]|(b[o+1]<<8),pi=b[o+2]|(b[o+3]<<8);
        if((pi===0x0039||pi===0x0E06)&&pt===0x0040){try{const lo=BigInt(b[o+8]|(b[o+9]<<8)|(b[o+10]<<16)|((b[o+11]<<24)>>>0)),hi=BigInt(b[o+12]|(b[o+13]<<8)|(b[o+14]<<16)|((b[o+15]<<24)>>>0));
          const ft=hi*BigInt(0x100000000)+lo,ms=Number((ft-BigInt("116444736000000000"))/BigInt(10000));
          if(ms>0&&ms<Date.now()+86400000){const d=new Date(ms);date=`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;break;}}catch(e){}}}}
    const from=senderEmail?`${senderName} <${senderEmail}>`:senderName;
    return{subject,from,date,body:body.slice(0,500)};
  }catch(e){console.error("MSG parse:",e);return null;}
}

const CNZ_FIELDS={container_id:{col:0,label:"Container / Reference ID",desc:"Container number or shipment reference",kw:["container","shipment","consignment","booking","reference","ref","bill of lading","bol","bl","delivery","po number","purchase order","asn","receipt","inbound","tracking"],fromFilename:true},material:{col:4,label:"Material / SKU Code",desc:"Product code, material number, or SKU",kw:["material","sku","product","item code","article","part number","part no","upc","ean","barcode","product code","item number","item no","stock code","catalog","gtin"]},quantity:{col:5,label:"Quantity (EA)",desc:"Total quantity in eaches",kw:["actual delivery qty","quantity","qty","units","total qty","ship qty","shipped","received","ea qty","each","pieces","pcs","count","delivery qty","order qty","actual qty"]},batch:{col:6,label:"Batch / Lot Number",desc:"Batch, lot, or vintage code",kw:["batch","lot","lot number","lot no","vintage","batch number","batch no","lot code","production batch","expiry","best before","bbe"]}};
const CNZ_STATIC=[{col:9,label:"Location",value:"DOCK"},{col:18,label:"System Set",value:"SYSTEMSET"},{col:20,label:"Pallet Type",value:"CHEP PALLET"},{col:25,label:"Create Multiple MUs",value:"CreateMultipleMUs:TRUE"}];
const CNZ_TOTAL=26;
function cnzNorm(t){return String(t).toLowerCase().replace(/[^a-z0-9 ]/g,"").trim();}
function cnzScore(src,kws){const nc=cnzNorm(src);let best=0;for(const kw of kws){const nk=cnzNorm(kw);if(nc===nk)return 1;if(nk.includes(nc)||nc.includes(nk))best=Math.max(best,0.85);const cw=new Set(nc.split(/\s+/)),ks=new Set(nk.split(/\s+/));let ov=0;cw.forEach(w=>{if(ks.has(w))ov++;});if(cw.size&&ks.size)best=Math.max(best,ov/Math.max(cw.size,ks.size)*0.9);}return best;}
function cnzAutoMap(cols){const sc=[];for(const[fn,fd]of Object.entries(CNZ_FIELDS)){if(fd.fromFilename)continue;for(const c of cols)sc.push({s:cnzScore(c,fd.kw),fn,c});}sc.sort((a,b)=>b.s-a.s);const m={},u=new Set();for(const{s,fn,c}of sc){if(m[fn]||u.has(c))continue;if(s>=0.3){m[fn]={col:c,conf:s};u.add(c);}}return m;}
function cnzExtractContainer(fn){const n=fn.replace(/\.[^.]+$/,"").toUpperCase();for(const p of[/[A-Z]{4}\d{7}/,/[A-Z]{3}U\d{7}/,/[A-Z]{2,4}\d{5,}/]){const m=n.match(p);if(m)return m[0];}return fn.replace(/\.[^.]+$/,"");}

const Card=({title,value,sub,color=C.blue,icon})=>(<div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"18px 22px",flex:1,minWidth:140}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{color:C.text2,fontSize:10,fontWeight:700,textTransform:"uppercase",letterSpacing:1.2}}>{title}</span>{icon&&<span style={{fontSize:16}}>{icon}</span>}</div><div style={{color,fontSize:30,fontWeight:800,marginTop:6,lineHeight:1}}>{value}</div>{sub&&<div style={{color:C.text3,fontSize:11,marginTop:4}}>{sub}</div>}</div>);
const Btn=({children,bg=C.blue,onClick,disabled,small,icon:Icon,style:s2})=>(<button onClick={onClick} disabled={disabled} style={{background:disabled?"#333":bg,color:C.white,border:"none",borderRadius:6,padding:small?"5px 12px":"8px 18px",fontWeight:700,fontSize:small?11:12,cursor:disabled?"default":"pointer",opacity:disabled?0.5:1,display:"inline-flex",alignItems:"center",gap:6,transition:"all 0.15s",...s2}}>{Icon&&<Icon size={small?13:15}/>}{children}</button>);
const Sel=({value,onChange,options,width=200})=>(<select value={value} onChange={e=>onChange(e.target.value)} style={{background:C.bg3,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"7px 10px",fontSize:12,width,outline:"none"}}>{options.map(o=><option key={o} value={o}>{o}</option>)}</select>);
const SH=({icon:Icon,title,sub})=>(<div style={{marginBottom:14}}><div style={{display:"flex",alignItems:"center",gap:8}}>{Icon&&<Icon size={20} color={C.blue}/>}<span style={{color:C.text,fontSize:18,fontWeight:800}}>{title}</span></div>{sub&&<div style={{color:C.text3,fontSize:12,marginTop:2,marginLeft:28}}>{sub}</div>}</div>);
const Badge=({children,bg,color=C.white})=>(<span style={{background:bg,color,fontSize:10,fontWeight:700,padding:"3px 8px",borderRadius:4,whiteSpace:"nowrap"}}>{children}</span>);

export default function App(){
  const [tab,setTab]=useState("home");const [sideOpen,setSideOpen]=useState(true);const now=new Date();
  const [cnzSrc,setCnzSrc]=useState(null);const [cnzCols,setCnzCols]=useState([]);const [cnzFile,setCnzFile]=useState("");const [cnzMap,setCnzMap]=useState({});const [cnzContainer,setCnzContainer]=useState("");const [cnzContainerCol,setCnzContainerCol]=useState("");const [cnzPreview,setCnzPreview]=useState(false);
  const [cnzProfiles,setCnzProfiles]=useState(()=>{try{return JSON.parse(window._cnzProfiles||"{}");} catch(e){return{};}});const [cnzProfileName,setCnzProfileName]=useState("");const cnzRef=useRef();
  const EMAIL_CATS=["Order Creation","Stock Check","Stocktake","Cancel Order","Client Request","Inwards/Receipt","Dispatch Query","Returns","Compliance/H&S","Internal","Other"];
  const DKW={"order creation":["new order","order creation","purchase order","po #","create order"],"stock check":["stock check","stock query","stock level","inventory check","how many","availability"],"stocktake":["stocktake","stock take","cycle count","inventory count"],"cancel order":["cancel","cancellation","cancel order","void order"],"client request":["request","can you","could you","would like","asking for"],"inwards/receipt":["inwards","receipt","receiving","container","inbound","delivery","shipment","asn"],"dispatch query":["dispatch","shipping","tracking","freight","courier","pickup","collection"],"returns":["return","rma","send back","credit","damaged","faulty"],"compliance/h&s":["incident","near miss","accident","safety","hazard","audit","compliance"],"internal":["meeting","roster","shift","leave","training","toolbox"]};
  const [emailRows,setEmailRows]=useState([]);const [emailFile,setEmailFile]=useState("");
  const initMem={learnedKeywords:{},categoryTimes:{"Order Creation":0.5,"Stock Check":0.25,"Stocktake":1.0,"Cancel Order":0.25,"Client Request":0.5,"Inwards/Receipt":0.5,"Dispatch Query":0.25,"Returns":0.5,"Compliance/H&S":0.5,"Internal":0.25,"Other":0.25},clientPatterns:{},history:[]};
  const [emailMem,setEmailMem]=useState(()=>{try{const v=window._emailMem;return v?{...initMem,...JSON.parse(v)}:{...initMem};}catch(e){return{...initMem};}});
  const mem=emailMem||initMem;const [emailMonth,setEmailMonth]=useState(`${now.getFullYear()}-${pad(now.getMonth()+1)}`);const emailRef=useRef();
  const [skuClients,setSkuClients]=useState(()=>{try{const v=window._skuClients;return v?JSON.parse(v):{};}catch(e){return{};}});
  const [skuActive,setSkuActive]=useState("");const [skuNewName,setSkuNewName]=useState("");const [skuInwards,setSkuInwards]=useState([]);const [skuPaste,setSkuPaste]=useState("");const [skuFilter,setSkuFilter]=useState("all");const [skuSearch,setSkuSearch]=useState("");const skuMRef=useRef();const skuIRef=useRef();
  const saveSku=(d)=>{setSkuClients(d);try{window._skuClients=JSON.stringify(d);}catch(e){}};
  const saveMem=(m)=>{setEmailMem(m);window._emailMem=JSON.stringify(m);};
  const classify=(subj,from,body)=>{const t=(subj+" "+from+" "+(body||"")).toLowerCase();for(const[kw,cat]of Object.entries(mem.learnedKeywords)){if(t.includes(kw.toLowerCase()))return cat;}for(const[ck,kws]of Object.entries(DKW)){const cn=EMAIL_CATS.find(c=>c.toLowerCase()===ck)||"Other";for(const kw of kws){if(t.includes(kw.toLowerCase()))return cn;}}return"Other";};
  const defTime=(cat)=>mem.categoryTimes[cat]??0.25;
  const detectClient=(from,subj)=>{for(const[p,cl]of Object.entries(mem.clientPatterns)){if(from.toLowerCase().includes(p.toLowerCase()))return cl;}const m=from.match(/@([^.]+)/);return m?m[1].charAt(0).toUpperCase()+m[1].slice(1):"Unknown";};

  const handleSkuMaster=useCallback((e)=>{const file=e.target.files[0];if(!file)return;const cn=skuNewName.trim()||skuActive||file.name.replace(/\.[^.]+$/,"");const ext=file.name.split(".").pop().toLowerCase();
    const proc=(rows,hds)=>{const sc=findCol(hds,["SKU","sku","Item Code","ItemCode","Material","Product Code","Barcode","Article"]),dc=findCol(hds,["ItemDescription","Item Description","Description","Product Name","Name"]),uc=findCol(hds,["InvUOM","UOM","Unit"]),upc=findCol(hds,["UPC","EAN","Barcode","GTIN"]),tb=findCol(hds,["Trackbys","TrackBy","Track By"]),tr=findCol(hds,["TrackbyReq","TrackBy Required","Track By Required"]),d2=findCol(hds,["Description2","Description 2","Desc2"]),du=findCol(hds,["DIMUOM","Dim UOM"]),un=findCol(hds,["NumofInvUnits","Units Per"]),wt=findCol(hds,["WeightKgs","Weight"]);
      const mr=rows.map(r=>{const s=String(r[sc]||"").trim();if(!s)return null;return{sku:s,desc:dc?String(r[dc]||"").trim():"",uom:uc?String(r[uc]||"").trim():"",upc:upc?String(r[upc]||"").trim():"",trackby:tb?String(r[tb]||"").trim():"",trackbyReq:tr?String(r[tr]||"").trim():"",desc2:d2?String(r[d2]||"").trim():"",dimUom:du?String(r[du]||"").trim():"",units:un?r[un]:"",weight:wt?r[wt]:""};}).filter(Boolean);
      const up={...skuClients,[cn]:{skus:mr,fileName:file.name,loadedAt:new Date().toISOString(),count:mr.length}};saveSku(up);setSkuActive(cn);setSkuNewName("");};
    if(ext==="csv"){Papa.parse(file,{header:true,skipEmptyLines:true,complete:(r)=>{proc(r.data,r.meta.fields||[]);}});}
    else{const rd=new FileReader();rd.onload=(ev)=>{const wb=XLSX.read(ev.target.result,{type:"array"});let sn=wb.SheetNames[0];for(const s of wb.SheetNames){const l=s.toLowerCase();if(l.includes("master")||l.includes("sku")||l.includes("client"))sn=s;}const json=XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:""});proc(json,json.length?Object.keys(json[0]):[]);};rd.readAsArrayBuffer(file);}e.target.value="";},[skuClients,skuActive,skuNewName]);

  const runCheck=(list)=>{const cl=skuClients[skuActive];if(!cl)return;const mm={};cl.skus.forEach(m=>{mm[m.sku.toUpperCase().trim()]=m;});
    setSkuInwards(list.map((s,i)=>{const mt=mm[s.toUpperCase().trim()];return{id:i,sku:s,status:mt?"On Master":"Needs Creating",desc:mt?.desc||"",uom:mt?.uom||"",upc:mt?.upc||"",trackby:mt?.trackby||"",trackbyReq:mt?.trackbyReq||"Not found",desc2:mt?.desc2||""};}));};

  const handleSkuInFile=useCallback((e)=>{const file=e.target.files[0];if(!file)return;const ext=file.name.split(".").pop().toLowerCase();
    const proc=(rows,hds)=>{const sc=findCol(hds,["SKU","sku","Item Code","ItemCode","Material","Product Code","Barcode","Article"])||hds[0];runCheck(rows.map(r=>String(r[sc]||"").trim()).filter(Boolean));};
    if(ext==="csv"){Papa.parse(file,{header:true,skipEmptyLines:true,complete:(r)=>{proc(r.data,r.meta.fields||[]);}});}
    else{const rd=new FileReader();rd.onload=(ev)=>{const wb=XLSX.read(ev.target.result,{type:"array"});const json=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});proc(json,json.length?Object.keys(json[0]):[]);};rd.readAsArrayBuffer(file);}e.target.value="";},[skuClients,skuActive]);

  const skuStats=useMemo(()=>{const t=skuInwards.length,on=skuInwards.filter(r=>r.status==="On Master").length;return{total:t,onMaster:on,nc:t-on};},[skuInwards]);
  const filtSku=useMemo(()=>skuFilter==="needs_creating"?skuInwards.filter(r=>r.status==="Needs Creating"):skuFilter==="on_master"?skuInwards.filter(r=>r.status==="On Master"):skuInwards,[skuInwards,skuFilter]);
  const masterSearch=useMemo(()=>{if(!skuSearch||!skuClients[skuActive])return[];const q=skuSearch.toLowerCase();return skuClients[skuActive].skus.filter(m=>m.sku.toLowerCase().includes(q)||m.desc.toLowerCase().includes(q)||m.upc.toLowerCase().includes(q)).slice(0,50);},[skuSearch,skuActive,skuClients]);
  const exportSku=()=>{if(!skuInwards.length)return;const ws=XLSX.utils.json_to_sheet(skuInwards.map(r=>({SKU:r.sku,Status:r.status,Description:r.desc,UOM:r.uom,UPC:r.upc,TrackBy:r.trackby,TrackByRequired:r.trackbyReq})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"SKU Check");const nc=skuInwards.filter(r=>r.status==="Needs Creating");if(nc.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(nc.map(r=>({SKU:r.sku}))),"Needs Creating");XLSX.writeFile(wb,`SKU_Check_${skuActive}_${new Date().toISOString().slice(0,10)}.xlsx`);};

  const [emailLoading,setEmailLoading]=useState(false);
  const handleEmailFiles=useCallback((e)=>{const files=Array.from(e.target.files);if(!files.length)return;
    const msgFiles=files.filter(f=>f.name.toLowerCase().endsWith(".msg"));
    const csvFile=files.find(f=>f.name.toLowerCase().endsWith(".csv"));
    // CSV path
    if(csvFile&&!msgFiles.length){setEmailFile(csvFile.name);
      Papa.parse(csvFile,{header:true,skipEmptyLines:true,complete:(r)=>{const h=r.meta.fields||[];const sc=findCol(h,["Subject","subject","Title"])||h[0],fc=findCol(h,["From","from","Sender"])||h.find(x=>x.toLowerCase().includes("from")),dc=findCol(h,["Received","Date","date","Sent"])||h.find(x=>x.toLowerCase().includes("date")),bc=findCol(h,["Body","body","Message","Content"]);
        setEmailRows(r.data.map((row,i)=>{const s=String(row[sc]||"").trim(),f=String(row[fc]||"").trim(),d=String(row[dc]||"").trim(),b=bc?String(row[bc]||"").trim():"";if(!s&&!f)return null;const cat=classify(s,f,b);return{id:i,subject:s,from:f,date:d,body:b.slice(0,200),category:cat,client:detectClient(f,s),time:defTime(cat),confirmed:false};}).filter(Boolean));}});e.target.value="";return;}
    // MSG path
    if(msgFiles.length){setEmailFile(`${msgFiles.length} .msg files`);setEmailLoading(true);
      const results=[];let done=0;
      msgFiles.forEach((file,idx)=>{const reader=new FileReader();reader.onload=(ev)=>{
        const parsed=parseMSG(new Uint8Array(ev.target.result));
        if(parsed&&(parsed.subject||parsed.from)){const cat=classify(parsed.subject,parsed.from,parsed.body);
          results.push({id:idx,subject:parsed.subject,from:parsed.from,date:parsed.date,body:(parsed.body||"").slice(0,200),category:cat,client:detectClient(parsed.from,parsed.subject),time:defTime(cat),confirmed:false});}
        done++;if(done===msgFiles.length){results.sort((a,b)=>(a.date||"").localeCompare(b.date||""));results.forEach((r,i)=>r.id=i);setEmailRows(results);setEmailLoading(false);}
      };reader.readAsArrayBuffer(file);});e.target.value="";return;}
    e.target.value="";},[mem]);
  const updateEmail=(id,field,val)=>{setEmailRows(prev=>prev.map(r=>{if(r.id!==id)return r;const u={...r,[field]:val,confirmed:true};if(field==="category"){const w=r.subject.toLowerCase().split(/\s+/).filter(w=>w.length>3);if(w.length)saveMem({...mem,learnedKeywords:{...mem.learnedKeywords,[w.slice(0,3).join(" ")]:val}});u.time=defTime(val);}if(field==="time"){u.time=parseFloat(val)||0.25;saveMem({...mem,categoryTimes:{...mem.categoryTimes,[r.category]:u.time}});}if(field==="client"&&r.from){const m=r.from.match(/@([^.]+)/);if(m)saveMem({...mem,clientPatterns:{...mem.clientPatterns,[m[1]]:val}});}return u;}));};
  const emailSum=useMemo(()=>{const cats={};let tt=0;const cls={};emailRows.forEach(r=>{if(!cats[r.category])cats[r.category]={count:0,time:0};cats[r.category].count++;cats[r.category].time+=r.time;tt+=r.time;if(!cls[r.client])cls[r.client]={count:0,time:0};cls[r.client].count++;cls[r.client].time+=r.time;});return{cats,totalTime:tt,clients:cls,total:emailRows.length};},[emailRows]);
  const exportEmail=()=>{if(!emailRows.length)return;const ws=XLSX.utils.json_to_sheet(emailRows.map(r=>({Date:r.date,From:r.from,Subject:r.subject,Category:r.category,Client:r.client,"Time (hrs)":r.time})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Log");const sd=Object.entries(emailSum.cats).map(([c,d])=>({Category:c,Count:d.count,Hours:Math.round(d.time*100)/100}));sd.push({Category:"TOTAL",Count:emailSum.total,Hours:Math.round(emailSum.totalTime*100)/100});XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sd),"Summary");XLSX.writeFile(wb,`Email_Log_${emailMonth}.xlsx`);};
  const confirmAll=()=>{setEmailRows(p=>p.map(r=>({...r,confirmed:true})));const tc={};emailRows.forEach(r=>{(tc[r.category]??=[]).push(r.time);});const at={};for(const[c,t]of Object.entries(tc))at[c]=Math.round(t.reduce((a,b)=>a+b,0)/t.length*100)/100;saveMem({...mem,categoryTimes:{...mem.categoryTimes,...at},history:[...mem.history,{month:emailMonth,total:emailSum.total,hours:Math.round(emailSum.totalTime*100)/100,date:new Date().toISOString()}]});};

  const saveProf=(n)=>{if(!n.trim())return;const p={...cnzProfiles,[n.trim()]:{...cnzMap,_cc:cnzContainerCol}};setCnzProfiles(p);window._cnzProfiles=JSON.stringify(p);};
  const loadProf=(n)=>{const p=cnzProfiles[n];if(!p)return;const m={...p};const cc=m._cc||"";delete m._cc;setCnzMap(m);setCnzContainerCol(cc);};
  const delProf=(n)=>{const p={...cnzProfiles};delete p[n];setCnzProfiles(p);window._cnzProfiles=JSON.stringify(p);};
  const handleCnzFile=useCallback((e)=>{const file=e.target.files[0];if(!file)return;setCnzFile(file.name);setCnzPreview(false);const ext=file.name.split(".").pop().toLowerCase();
    if(ext==="csv"){Papa.parse(file,{header:true,skipEmptyLines:true,complete:(r)=>{setCnzCols(r.meta.fields||[]);setCnzSrc(r.data);setCnzMap(cnzAutoMap(r.meta.fields||[]));setCnzContainer(cnzExtractContainer(file.name));setCnzContainerCol("");}});}
    else{const rd=new FileReader();rd.onload=(ev)=>{const wb=XLSX.read(ev.target.result,{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];const json=XLSX.utils.sheet_to_json(ws,{defval:""});const cols=json.length?Object.keys(json[0]):[];setCnzCols(cols);setCnzSrc(json);setCnzMap(cnzAutoMap(cols));setCnzContainer(cnzExtractContainer(file.name));setCnzContainerCol("");};rd.readAsArrayBuffer(file);}e.target.value="";},[]);
  const cnzBuild=useCallback(()=>{if(!cnzSrc)return[];return cnzSrc.map(row=>{const out=new Array(CNZ_TOTAL).fill("");if(cnzContainerCol&&cnzContainerCol!=="-- Not Mapped --")out[0]=row[cnzContainerCol]||"";else out[0]=cnzContainer;for(const[fn,fd]of Object.entries(CNZ_FIELDS)){if(fn==="container_id")continue;if(cnzMap[fn])out[fd.col]=row[cnzMap[fn].col]||"";}CNZ_STATIC.forEach(s=>{out[s.col]=s.value;});return out;});},[cnzSrc,cnzMap,cnzContainer,cnzContainerCol]);
  const cnzExport=useCallback(()=>{const out=cnzBuild();if(!out.length)return;const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(out),"Sheet 1");XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([]),"Sheet2");XLSX.writeFile(wb,`CNZ_Import_${cnzFile.replace(/\.[^.]+$/,"")}.xlsx`);},[cnzBuild,cnzFile]);

  const [winW,setWinW]=useState(typeof window!=="undefined"?window.innerWidth:1920);const [winH,setWinH]=useState(typeof window!=="undefined"?window.innerHeight:1080);
  useEffect(()=>{const h=()=>{setWinW(window.innerWidth);setWinH(window.innerHeight);};window.addEventListener("resize",h);return()=>window.removeEventListener("resize",h);},[]);
  const isC=winW<1024,isW=winW>=1920,isU=winW>=2400;const cp=isU?32:isW?24:isC?12:20;const sW=isC?0:sideOpen?(isU?260:220):56;const mx=isU?1800:isW?1500:9999;const sf=isU?1.15:isW?1.05:1;
  useEffect(()=>{if(isC&&sideOpen)setSideOpen(false);},[isC]);
  const nav=[{title:"Home",items:[{id:"home",label:"Overview",icon:Home}]},{title:"Tools",items:[{id:"cnz_mapper",label:"CNZ Mapper",icon:RefreshCw},{id:"email_classifier",label:"Email Classifier",icon:Mail},{id:"sku_checker",label:"SKU Checker",icon:Package}]}];

  const renderHome=()=>{const pn=Object.keys(cnzProfiles),lc=Object.keys(mem.learnedKeywords).length,cc=Object.keys(skuClients),ts=Object.values(skuClients).reduce((a,c)=>a+c.count,0);
    return(<div><SH icon={Home} title={`3PL Tools Hub — ${YEAR}`} sub="CNZ Mapper · Email Classifier · SKU Checker"/>
      <div style={{display:"grid",gridTemplateColumns:isC?"1fr":"1fr 1fr 1fr",gap:12}}>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:12,padding:20,cursor:"pointer"}} onClick={()=>setTab("cnz_mapper")} onMouseOver={e=>e.currentTarget.style.borderColor=C.orange} onMouseOut={e=>e.currentTarget.style.borderColor=C.border}>
          <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><RefreshCw size={18} color={C.orange}/><span style={{color:C.text,fontWeight:700,fontSize:14}}>CNZ Mapper</span><ChevronRight size={14} color={C.text3} style={{marginLeft:"auto"}}/></div>
          <div style={{color:C.orange,fontSize:32,fontWeight:800}}>{pn.length}</div><div style={{color:C.text3,fontSize:11,marginTop:4}}>saved profiles</div></div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:12,padding:20,cursor:"pointer"}} onClick={()=>setTab("email_classifier")} onMouseOver={e=>e.currentTarget.style.borderColor=C.purple} onMouseOut={e=>e.currentTarget.style.borderColor=C.border}>
          <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><Mail size={18} color={C.purple}/><span style={{color:C.text,fontWeight:700,fontSize:14}}>Email Classifier</span><ChevronRight size={14} color={C.text3} style={{marginLeft:"auto"}}/></div>
          <div style={{color:C.purple,fontSize:32,fontWeight:800}}>{lc}</div><div style={{color:C.text3,fontSize:11,marginTop:4}}>keywords · {mem.history.length} months</div></div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:12,padding:20,cursor:"pointer"}} onClick={()=>setTab("sku_checker")} onMouseOver={e=>e.currentTarget.style.borderColor=C.cyan} onMouseOut={e=>e.currentTarget.style.borderColor=C.border}>
          <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><Package size={18} color={C.cyan}/><span style={{color:C.text,fontWeight:700,fontSize:14}}>SKU Checker</span><ChevronRight size={14} color={C.text3} style={{marginLeft:"auto"}}/></div>
          <div style={{color:C.cyan,fontSize:32,fontWeight:800}}>{cc.length}</div><div style={{color:C.text3,fontSize:11,marginTop:4}}>{cc.length===1?"client":"clients"} · {ts.toLocaleString()} SKUs</div>
          {cc.length>0&&<div style={{display:"flex",flexWrap:"wrap",gap:3,marginTop:8}}>{cc.map(n=>(<div key={n} style={{background:C.bg2,borderRadius:5,padding:"3px 8px"}}><span style={{color:C.cyan,fontSize:9,fontWeight:600}}>{n} ({skuClients[n].count})</span></div>))}</div>}</div>
      </div>
      <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:12,padding:20,marginTop:12}}>
        <div style={{color:C.text,fontWeight:700,fontSize:14,marginBottom:12}}>Quick Actions</div>
        <div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Btn bg={C.orange} onClick={()=>setTab("cnz_mapper")} icon={RefreshCw}>CNZ Mapper</Btn><Btn bg={C.purple} onClick={()=>setTab("email_classifier")} icon={Mail}>Email Classifier</Btn><Btn bg={C.cyan} onClick={()=>setTab("sku_checker")} icon={Package}>SKU Checker</Btn></div></div></div>);};

  const renderSkuChecker=()=>{const cns=Object.keys(skuClients);const ad=skuClients[skuActive];const hr=skuInwards.length>0;
    return(<div><SH icon={Package} title="SKU Checker" sub="Check inwards SKUs against client master lists"/>
      <div style={{display:"grid",gridTemplateColumns:isC?"1fr":"1fr 1fr",gap:10,marginBottom:12}}>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}>
          <div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Client Master Profiles</div>
          {cns.length>0&&<div style={{display:"flex",gap:4,flexWrap:"wrap",marginBottom:10}}>{cns.map(n=>{const d=skuClients[n],ia=n===skuActive;return(<div key={n} onClick={()=>setSkuActive(n)} style={{background:ia?C.sideActive:C.bg2,border:`1px solid ${ia?C.cyan:C.border}`,borderRadius:8,padding:"10px 14px",cursor:"pointer",flex:"1 1 auto",minWidth:140}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{color:ia?C.cyan:C.text,fontSize:12,fontWeight:700}}>{n}</span><Trash2 size={12} color={C.red} style={{cursor:"pointer",opacity:0.6}} onClick={(e)=>{e.stopPropagation();if(confirm(`Delete ${n}?`)){const u={...skuClients};delete u[n];saveSku(u);if(skuActive===n)setSkuActive("");}}}/></div>
            <div style={{color:C.text3,fontSize:10,marginTop:4}}>{d.count.toLocaleString()} SKUs · {d.fileName}</div></div>);})}</div>}
          <div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}><input value={skuNewName} onChange={e=>setSkuNewName(e.target.value)} placeholder="New client name..." style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"7px 10px",fontSize:12,flex:1,minWidth:140}}/>
            <Btn small bg={C.cyan} onClick={()=>skuMRef.current?.click()} icon={Upload}>Upload Master</Btn><input ref={skuMRef} type="file" accept=".xlsx,.xls,.csv" onChange={handleSkuMaster} style={{display:"none"}}/></div>
          <div style={{color:C.text3,fontSize:10,marginTop:6}}>Upload client master SKU file (.xlsx / .csv)</div></div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}>
          <div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>{ad?`Active: ${skuActive}`:"No Client Selected"}</div>
          {ad?<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginBottom:10}}>
            <div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:C.cyan,fontSize:22,fontWeight:800}}>{ad.count.toLocaleString()}</div><div style={{color:C.text3,fontSize:9}}>Master SKUs</div></div>
            <div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:C.green,fontSize:22,fontWeight:800}}>{skuStats.onMaster}</div><div style={{color:C.text3,fontSize:9}}>On Master</div></div>
            <div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:skuStats.nc?C.red:C.text3,fontSize:22,fontWeight:800}}>{skuStats.nc}</div><div style={{color:C.text3,fontSize:9}}>Needs Creating</div></div></div>
            <div style={{color:C.text3,fontSize:10}}>Source: {ad.fileName}</div></>
          :<div style={{color:C.text3,fontSize:12,padding:"20px 0"}}>Select or upload a client master</div>}</div></div>

      {ad&&<div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px",marginBottom:12}}>
        <div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Check Inwards SKUs</div>
        <div style={{display:"flex",gap:8,alignItems:"flex-start",flexWrap:"wrap"}}>
          <div style={{flex:1,minWidth:250}}>
            <textarea value={skuPaste} onChange={e=>setSkuPaste(e.target.value)} placeholder="Paste SKUs (one per line, comma, or semicolon separated)..." style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"10px 12px",fontSize:12,fontFamily:"monospace",width:"100%",height:80,resize:"vertical",outline:"none"}}/>
            <div style={{display:"flex",gap:6,marginTop:6}}>
              <Btn small bg={C.cyan} onClick={()=>{const l=skuPaste.split(/[\n,;]+/).map(s=>s.trim()).filter(Boolean);if(l.length)runCheck(l);setSkuPaste("");}} disabled={!skuPaste.trim()} icon={Search}>Check</Btn>
              <Btn small bg="#e94560" onClick={()=>skuIRef.current?.click()} icon={Upload}>Upload</Btn><input ref={skuIRef} type="file" accept=".xlsx,.xls,.csv" onChange={handleSkuInFile} style={{display:"none"}}/>
              {hr&&<Btn small bg={C.green} onClick={exportSku} icon={Download}>Export</Btn>}{hr&&<Btn small bg="#2a2a3e" onClick={()=>setSkuInwards([])}>Clear</Btn>}</div></div>
          <div style={{minWidth:200}}><div style={{color:C.text3,fontSize:10,marginBottom:6}}>Search Master</div>
            <input value={skuSearch} onChange={e=>setSkuSearch(e.target.value)} placeholder="SKU, desc, UPC..." style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"7px 10px",fontSize:12,width:"100%"}}/></div></div></div>}

      {skuSearch&&masterSearch.length>0&&<div style={{background:C.bg3,border:`1px solid ${C.cyan}44`,borderRadius:10,padding:"12px 16px",marginBottom:12}}>
        <div style={{color:C.cyan,fontSize:11,fontWeight:700,marginBottom:8}}>Master: {masterSearch.length} results</div>
        <div style={{overflow:"auto",maxHeight:250}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr>{["SKU","Description","UOM","UPC","TrackBy","TrackBy Req"].map((h,i)=>(<th key={i} style={{background:C.bg2,color:C.text2,padding:"8px 10px",textAlign:"left",fontWeight:700,fontSize:10,borderBottom:`1px solid ${C.border}`,position:"sticky",top:0}}>{h}</th>))}</tr></thead>
          <tbody>{masterSearch.map((m,i)=>(<tr key={i} style={{background:i%2?C.rowAlt:C.bg3}}><td style={{padding:"6px 10px",color:C.cyan,fontFamily:"monospace",fontWeight:700,fontSize:11}}>{m.sku}</td><td style={{padding:"6px 10px",color:C.text,maxWidth:250,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{m.desc}</td><td style={{padding:"6px 10px",color:C.text2}}>{m.uom}</td><td style={{padding:"6px 10px",color:C.text3,fontFamily:"monospace",fontSize:10}}>{m.upc}</td><td style={{padding:"6px 10px",color:C.yellow,fontSize:10}}>{m.trackby}</td><td style={{padding:"6px 10px",color:C.orange,fontSize:10}}>{m.trackbyReq}</td></tr>))}</tbody></table></div></div>}

      {hr&&<><div style={{display:"flex",gap:8,marginBottom:12,flexWrap:"wrap"}}><Card title="Checked" value={skuStats.total} color={C.blue} icon="📋"/><Card title="On Master" value={skuStats.onMaster} sub={skuStats.total?`${(skuStats.onMaster/skuStats.total*100).toFixed(1)}%`:""} color={C.green} icon="✅"/><Card title="Needs Creating" value={skuStats.nc} sub={skuStats.nc?"action required":"all clear!"} color={skuStats.nc?C.red:C.green} icon={skuStats.nc?"⚠️":"✅"}/></div>
        <div style={{display:"flex",gap:6,marginBottom:10,alignItems:"center"}}><Filter size={14} color={C.text3}/>{[["all","All",C.blue],["on_master","On Master",C.green],["needs_creating","Needs Creating",C.red]].map(([v,l,cl])=>(<button key={v} onClick={()=>setSkuFilter(v)} style={{background:skuFilter===v?cl+"22":"transparent",color:skuFilter===v?cl:C.text3,border:`1px solid ${skuFilter===v?cl:C.border}`,borderRadius:6,padding:"5px 12px",fontSize:11,fontWeight:700,cursor:"pointer"}}>{l} ({v==="all"?skuStats.total:v==="on_master"?skuStats.onMaster:skuStats.nc})</button>))}</div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,overflow:"auto",maxHeight:500}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr>{["SKU","Status","Description","UOM","UPC","TrackBy Required","Desc2"].map((h,i)=>(<th key={i} style={{background:C.bg2,color:C.text2,padding:"10px 12px",textAlign:"left",fontWeight:700,fontSize:10,borderBottom:`1px solid ${C.border}`,whiteSpace:"nowrap",position:"sticky",top:0,zIndex:1}}>{h}</th>))}</tr></thead>
          <tbody>{filtSku.map((r,ri)=>{const on=r.status==="On Master";return(<tr key={r.id} style={{background:ri%2?C.rowAlt:C.bg3,borderLeft:`3px solid ${on?C.green:C.red}`}}><td style={{padding:"8px 12px",color:C.text,fontFamily:"monospace",fontWeight:700,fontSize:12}}>{r.sku}</td><td style={{padding:"8px 12px"}}><Badge bg={on?C.green+"22":C.red+"22"} color={on?C.green:C.red}>{r.status}</Badge></td><td style={{padding:"8px 12px",color:C.text,maxWidth:220,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{r.desc||"—"}</td><td style={{padding:"8px 12px",color:C.text2}}>{r.uom||"—"}</td><td style={{padding:"8px 12px",color:C.text3,fontFamily:"monospace",fontSize:10}}>{r.upc||"—"}</td><td style={{padding:"8px 12px",color:on?(r.trackbyReq.includes("Lot")?C.yellow:r.trackbyReq.includes("Not")?C.red:C.text2):C.red,fontSize:10,fontWeight:600}}>{r.trackbyReq||"—"}</td><td style={{padding:"8px 12px",color:C.text3,maxWidth:200,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",fontSize:10}}>{r.desc2||"—"}</td></tr>);})}</tbody></table></div>
        {skuStats.nc>0&&<div style={{background:C.bg3,border:`1px solid ${C.red}44`,borderRadius:10,padding:"14px 18px",marginTop:12}}>
          <div style={{color:C.red,fontSize:12,fontWeight:700,marginBottom:8}}>⚠️ {skuStats.nc} SKU{skuStats.nc>1?"s":""} need creating</div>
          <div style={{display:"flex",flexWrap:"wrap",gap:4}}>{skuInwards.filter(r=>r.status==="Needs Creating").map(r=>(<span key={r.id} style={{background:C.red+"18",color:C.red,fontSize:11,fontFamily:"monospace",fontWeight:600,padding:"3px 8px",borderRadius:4,border:`1px solid ${C.red}33`}}>{r.sku}</span>))}</div>
          <Btn small bg={C.red} onClick={()=>{navigator.clipboard?.writeText(skuInwards.filter(r=>r.status==="Needs Creating").map(r=>r.sku).join("\n"));}} icon={Copy} style={{marginTop:10}}>Copy to Clipboard</Btn></div>}</>}

      {!ad&&!cns.length&&<div style={{textAlign:"center",padding:50,color:C.text3}}><Database size={40} color={C.text3} style={{opacity:0.2,marginBottom:12}}/><div style={{fontSize:15,color:C.text2,marginBottom:6}}>How it works</div>
        <div style={{fontSize:12,lineHeight:1.8,maxWidth:520,margin:"0 auto",textAlign:"left"}}><span style={{color:C.cyan,fontWeight:700}}>1.</span> Upload a <strong style={{color:C.text}}>Client Master SKU</strong> file from your WMS<br/><span style={{color:C.cyan,fontWeight:700}}>2.</span> Stored as a <strong style={{color:C.text}}>client profile</strong> — add multiple clients<br/><span style={{color:C.cyan,fontWeight:700}}>3.</span> Paste or upload incoming SKUs<br/><span style={{color:C.cyan,fontWeight:700}}>4.</span> See <span style={{color:C.green,fontWeight:700}}>On Master</span> vs <span style={{color:C.red,fontWeight:700}}>Needs Creating</span><br/><span style={{color:C.cyan,fontWeight:700}}>5.</span> See <span style={{color:C.yellow}}>tracking requirements</span> (Lot#, Expiry, SN)<br/><span style={{color:C.cyan,fontWeight:700}}>6.</span> Export or copy "Needs Creating" list</div></div>}
    </div>);};

  const renderCnzMapper=()=>{const srcOpts=["-- Not Mapped --",...cnzCols];const confClr=c=>c>=0.7?C.green:c>=0.5?C.yellow:C.red;const samples=(col)=>cnzSrc?cnzSrc.slice(0,3).map(r=>r[col]).filter(v=>v!=null&&v!=="").join(", ").slice(0,80):"";const pd=cnzPreview?cnzBuild().slice(0,20):[];const cl=Array.from({length:CNZ_TOTAL}).map((_,i)=>String.fromCharCode(65+i));const pn=Object.keys(cnzProfiles);
    return(<div><SH icon={RefreshCw} title="CNZ Import Mapper" sub="Map client files to CNZ Import Template"/>
      <div style={{display:"grid",gridTemplateColumns:isC?"1fr":"1fr 1fr",gap:10,marginBottom:12}}>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}><div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Source File</div>
          <div style={{display:"flex",alignItems:"center",gap:10}}><Btn bg="#e94560" onClick={()=>cnzRef.current?.click()} icon={Upload}>Browse</Btn><input ref={cnzRef} type="file" accept=".xlsx,.xls,.csv" onChange={handleCnzFile} style={{display:"none"}}/><span style={{color:cnzFile?C.text:C.text3,fontSize:12}}>{cnzFile||"No file"}</span></div>
          {cnzSrc&&<div style={{color:C.text2,fontSize:11,marginTop:8}}>{cnzSrc.length} rows · {cnzCols.length} cols · {Object.keys(cnzMap).length} mapped</div>}</div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}><div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Profiles</div>
          <div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}><input value={cnzProfileName} onChange={e=>setCnzProfileName(e.target.value)} placeholder="Name..." style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"6px 10px",fontSize:12,width:130}}/><Btn small bg={C.green} onClick={()=>{saveProf(cnzProfileName);setCnzProfileName("");}} disabled={!cnzProfileName.trim()||!cnzSrc} icon={Save}>Save</Btn>{pn.length>0&&<Sel value="" onChange={v=>{if(v)loadProf(v);}} options={["Load...",...pn]} width={140}/>}</div>
          {pn.length>0&&<div style={{display:"flex",gap:4,marginTop:8,flexWrap:"wrap"}}>{pn.map(n=>(<div key={n} style={{background:C.bg2,borderRadius:6,padding:"4px 10px",display:"flex",alignItems:"center",gap:6}}><span style={{color:C.text2,fontSize:11,cursor:"pointer"}} onClick={()=>loadProf(n)}>{n}</span><Trash2 size={12} color={C.red} style={{cursor:"pointer"}} onClick={()=>delProf(n)}/></div>))}</div>}</div></div>
      {cnzSrc&&<><div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"12px 18px",marginBottom:5}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:8}}><div><div style={{color:C.text,fontSize:12,fontWeight:700}}>Container ID <span style={{color:C.text3,fontWeight:400}}>(Col A)</span></div></div>
        <div style={{display:"flex",gap:6,alignItems:"center"}}><input value={cnzContainer} onChange={e=>setCnzContainer(e.target.value)} style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"6px 10px",fontSize:12,fontFamily:"monospace",width:180}}/><Sel value={cnzContainerCol||"-- Not Mapped --"} onChange={v=>setCnzContainerCol(v==="-- Not Mapped --"?"":v)} options={srcOpts} width={220}/></div></div></div>
        {Object.entries(CNZ_FIELDS).filter(([k,v])=>!v.fromFilename).map(([fn,fd])=>{const m=cnzMap[fn];return(<div key={fn} style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"12px 18px",marginBottom:5}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:8}}>
          <div><div style={{color:C.text,fontSize:12,fontWeight:700}}>{fd.label} <span style={{color:C.text3,fontWeight:400}}>(Col {String.fromCharCode(65+fd.col)})</span></div><div style={{color:C.text3,fontSize:10}}>{fd.desc}</div>
            {m&&<div style={{fontSize:10,marginTop:2}}><span style={{color:confClr(m.conf),fontWeight:700}}>✦ {(m.conf*100).toFixed(0)}%</span><span style={{color:C.text3,marginLeft:8}}>{samples(m.col)}</span></div>}</div>
          <Sel value={m?.col||"-- Not Mapped --"} onChange={v=>{setCnzMap(p=>{const n={...p};if(v==="-- Not Mapped --")delete n[fn];else n[fn]={col:v,conf:1};return n;});}} options={srcOpts} width={260}/></div></div>);})}
        <div style={{color:C.text2,fontSize:11,fontWeight:700,marginTop:12,marginBottom:5,textTransform:"uppercase",letterSpacing:1}}>Static</div>
        {CNZ_STATIC.map((s,i)=>(<div key={i} style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"8px 18px",marginBottom:3}}><span style={{color:C.text3,fontSize:11}}>Col {String.fromCharCode(65+s.col)}: {s.label} → <span style={{color:C.text,fontFamily:"monospace"}}>"{s.value}"</span></span></div>))}
        <div style={{display:"flex",gap:8,marginTop:14}}><Btn bg={C.purple} onClick={()=>setCnzPreview(!cnzPreview)} icon={cnzPreview?EyeOff:Eye}>{cnzPreview?"Hide":"Preview"}</Btn><Btn bg={C.green} onClick={cnzExport} icon={Download}>Export</Btn></div>
        {cnzPreview&&pd.length>0&&<div style={{marginTop:12,overflow:"auto",maxHeight:350,background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10}}><table style={{borderCollapse:"collapse",fontSize:10,whiteSpace:"nowrap"}}><thead><tr>{cl.map(l=><th key={l} style={{background:C.bg2,color:C.text2,padding:"7px 10px",borderBottom:`1px solid ${C.border}`,fontSize:10,fontWeight:700,position:"sticky",top:0}}>{l}</th>)}</tr></thead><tbody>{pd.map((row,ri)=>(<tr key={ri} style={{background:ri%2?C.rowAlt:C.bg3}}>{row.map((c,ci)=><td key={ci} style={{padding:"5px 10px",color:C.text,borderBottom:`1px solid ${C.border}18`}}>{c||""}</td>)}</tr>))}</tbody></table></div>}</>}
      {!cnzSrc&&<div style={{textAlign:"center",padding:50,color:C.text3}}><RefreshCw size={40} color={C.text3} style={{opacity:0.4,marginBottom:12}}/><div style={{fontSize:14}}>Upload Excel or CSV to begin</div></div>}</div>);};

  const renderEmailClassifier=()=>{const ec={"Order Creation":C.blue,"Stock Check":C.purple,"Stocktake":C.yellow,"Cancel Order":C.red,"Client Request":C.green,"Inwards/Receipt":C.orange,"Dispatch Query":C.cyan,"Returns":C.pink,"Compliance/H&S":"#f43f5e","Internal":C.text3,"Other":"#64748b"};const ft=(h)=>{const hrs=Math.floor(h),mins=Math.round((h-hrs)*60);return hrs>0?`${hrs}h ${mins}m`:`${mins}m`;};const lc=Object.keys(mem.learnedKeywords).length;
    return(<div><SH icon={Mail} title="Email Classifier" sub="Upload .msg files or CSV → classify → track time"/>
      <div style={{display:"grid",gridTemplateColumns:isC?"1fr":"1fr 1fr",gap:10,marginBottom:12}}>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}><div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Upload (.msg or .csv)</div>
          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}><Btn bg="#e94560" onClick={()=>emailRef.current?.click()} icon={Upload}>Browse Files</Btn><input ref={emailRef} type="file" accept=".csv,.msg" multiple onChange={handleEmailFiles} style={{display:"none"}}/><span style={{color:emailFile?C.text:C.text3,fontSize:12}}>{emailLoading?"Parsing...":emailFile||"No file"}</span></div>
          <div style={{display:"flex",gap:6,alignItems:"center"}}><span style={{color:C.text3,fontSize:11}}>Month:</span><input value={emailMonth} onChange={e=>setEmailMonth(e.target.value)} style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:6,padding:"5px 10px",fontSize:12,width:120}}/></div></div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}><div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Memory</div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8}}><div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:C.blue,fontSize:22,fontWeight:800}}>{lc}</div><div style={{color:C.text3,fontSize:9}}>Keywords</div></div><div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:C.green,fontSize:22,fontWeight:800}}>{Object.keys(mem.clientPatterns).length}</div><div style={{color:C.text3,fontSize:9}}>Clients</div></div><div style={{background:C.bg2,borderRadius:8,padding:"10px 12px",textAlign:"center"}}><div style={{color:C.purple,fontSize:22,fontWeight:800}}>{mem.history.length}</div><div style={{color:C.text3,fontSize:9}}>Months</div></div></div>
          <div style={{display:"flex",gap:6,marginTop:10}}><Btn small bg="#2a2a3e" onClick={()=>{if(confirm("Reset?"))saveMem({...mem,learnedKeywords:{},clientPatterns:{}});}}>Reset KW</Btn></div></div></div>
      {emailRows.length>0&&<><div style={{display:"flex",gap:8,marginBottom:12,flexWrap:"wrap"}}><Card title="Emails" value={emailSum.total} color={C.blue} icon="📧"/><Card title="Time" value={ft(emailSum.totalTime)} sub={`${emailSum.totalTime.toFixed(2)}h`} color={C.yellow} icon="⏱"/><Card title="Categories" value={Object.keys(emailSum.cats).length} color={C.purple} icon="📂"/></div>
        <div style={{display:"grid",gridTemplateColumns:isC?"1fr":"2fr 1fr",gap:10,marginBottom:12}}>
          <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}><div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Categories</div>
            {Object.entries(emailSum.cats).sort((a,b)=>b[1].count-a[1].count).map(([cat,d])=>(<div key={cat} style={{display:"flex",alignItems:"center",gap:10,marginBottom:6}}><div style={{width:10,height:10,borderRadius:3,background:ec[cat]||C.text3}}/><span style={{color:C.text,fontSize:12,fontWeight:600,width:140}}>{cat}</span><div style={{flex:1,background:C.bg,height:18,borderRadius:4,overflow:"hidden"}}><div style={{background:ec[cat]||C.text3,height:"100%",width:`${Math.max(d.count/emailSum.total*100,2)}%`,borderRadius:4}}/></div><span style={{color:C.text,fontSize:12,fontWeight:700,width:30,textAlign:"right"}}>{d.count}</span><span style={{color:C.yellow,fontSize:11,fontWeight:600,width:50,textAlign:"right"}}>{ft(d.time)}</span></div>))}</div>
          <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,padding:"16px 20px"}}><div style={{color:C.text2,fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:10}}>Clients</div>
            {Object.entries(emailSum.clients).sort((a,b)=>b[1].count-a[1].count).map(([cl,d])=>(<div key={cl} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",borderBottom:`1px solid ${C.border}22`}}><span style={{color:C.text,fontSize:12}}>{cl}</span><span style={{color:C.yellow,fontSize:11,fontWeight:600}}>{d.count} · {ft(d.time)}</span></div>))}</div></div>
        <div style={{display:"flex",gap:8,marginBottom:12}}><Btn bg={C.green} onClick={confirmAll} icon={Save}>Confirm All</Btn><Btn bg={C.purple} onClick={exportEmail} icon={Download}>Export</Btn></div>
        <div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:10,overflow:"auto",maxHeight:500}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr>{["Date","From","Subject","Category","Client","Time",""].map((h,i)=>(<th key={i} style={{background:C.bg2,color:C.text2,padding:"10px 12px",textAlign:"left",fontWeight:700,fontSize:10,borderBottom:`1px solid ${C.border}`,whiteSpace:"nowrap",position:"sticky",top:0,zIndex:1}}>{h}</th>))}</tr></thead>
          <tbody>{emailRows.map((r,ri)=>(<tr key={r.id} style={{background:ri%2?C.rowAlt:C.bg3,borderLeft:r.confirmed?`3px solid ${C.green}`:`3px solid transparent`}}>
            <td style={{padding:"8px 12px",color:C.text3,whiteSpace:"nowrap",fontSize:10}}>{r.date}</td><td style={{padding:"8px 12px",color:C.text2,maxWidth:150,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{r.from}</td>
            <td style={{padding:"8px 12px",color:C.text,maxWidth:250,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}} title={r.subject}>{r.subject}</td>
            <td style={{padding:"8px 6px"}}><select value={r.category} onChange={e=>updateEmail(r.id,"category",e.target.value)} style={{background:C.bg2,color:ec[r.category]||C.text,border:`1px solid ${C.border}`,borderRadius:4,padding:"4px 6px",fontSize:11,fontWeight:600,width:130}}>{EMAIL_CATS.map(c=><option key={c} value={c}>{c}</option>)}</select></td>
            <td style={{padding:"8px 6px"}}><input value={r.client} onChange={e=>updateEmail(r.id,"client",e.target.value)} style={{background:C.bg2,color:C.text,border:`1px solid ${C.border}`,borderRadius:4,padding:"4px 6px",fontSize:11,width:100}}/></td>
            <td style={{padding:"8px 6px"}}><input type="number" step="0.25" min="0" value={r.time} onChange={e=>updateEmail(r.id,"time",parseFloat(e.target.value)||0)} style={{background:C.bg2,color:C.yellow,border:`1px solid ${C.border}`,borderRadius:4,padding:"4px 6px",fontSize:11,fontWeight:700,width:60,textAlign:"center"}}/></td>
            <td style={{padding:"8px 6px"}}>{r.confirmed&&<span style={{color:C.green}}>✓</span>}</td></tr>))}</tbody></table></div></>}
      {!emailRows.length&&<div style={{textAlign:"center",padding:50,color:C.text3}}><Mail size={40} color={C.text3} style={{opacity:0.2,marginBottom:12}}/><div style={{fontSize:15,color:C.text2,marginBottom:6}}>How to import emails</div>
        <div style={{fontSize:12,lineHeight:1.8,maxWidth:520,margin:"0 auto",textAlign:"left"}}>
          <div style={{color:C.cyan,fontWeight:700,marginBottom:4}}>Option 1: Drag .msg files (easiest)</div>
          <span style={{color:C.text3}}>In Outlook → select emails for the month → drag to a desktop folder → upload all .msg files here</span><br/><br/>
          <div style={{color:C.cyan,fontWeight:700,marginBottom:4}}>Option 2: CSV export</div>
          <span style={{color:C.text3}}>File → Open & Export → Import/Export → Export to File → CSV → pick folder & date range</span>
        </div></div>}</div>);};

  const renderContent=()=>{switch(tab){case"home":return renderHome();case"cnz_mapper":return renderCnzMapper();case"email_classifier":return renderEmailClassifier();case"sku_checker":return renderSkuChecker();default:return renderHome();}};

  return(<div style={{background:C.bg,minHeight:"100vh",color:C.text,fontFamily:"'Segoe UI',system-ui,-apple-system,sans-serif",display:"flex",fontSize:Math.round(14*sf)}}>
    {isC&&sideOpen&&<div onClick={()=>setSideOpen(false)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.6)",zIndex:90}}/>}
    <div style={{width:sW,background:C.sidebar,borderRight:`1px solid ${C.border}`,display:"flex",flexDirection:"column",transition:"width 0.2s,transform 0.2s",flexShrink:0,overflow:"hidden",...(isC?{position:"fixed",left:0,top:0,bottom:0,width:240,zIndex:100,transform:sideOpen?"translateX(0)":"translateX(-100%)"}:{})}}>
      <div style={{padding:(sideOpen||isC)?"16px 16px 12px":"16px 12px 12px",borderBottom:`1px solid ${C.border}`,display:"flex",alignItems:"center",gap:10,cursor:"pointer"}} onClick={()=>setSideOpen(!sideOpen)}>
        <div style={{width:34,height:34,borderRadius:8,background:`linear-gradient(135deg,${C.orange},${C.cyan})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:17,flexShrink:0}}>🔧</div>
        {(sideOpen||isC)&&<div><div style={{color:C.text,fontSize:14,fontWeight:800}}>3PL Tools</div><div style={{color:C.text3,fontSize:10}}>{YEAR}</div></div>}</div>
      <div style={{flex:1,overflowY:"auto",padding:"8px 0"}}>{nav.map((sec,si)=>(<div key={si} style={{marginBottom:4}}>
        {(sideOpen||isC)&&<div style={{color:C.text3,fontSize:9,fontWeight:700,textTransform:"uppercase",letterSpacing:1.5,padding:"8px 16px 4px"}}>{sec.title}</div>}
        {sec.items.map(item=>{const a=tab===item.id;const I=item.icon;return(<div key={item.id} onClick={()=>{setTab(item.id);if(isC)setSideOpen(false);}} style={{display:"flex",alignItems:"center",gap:10,padding:(sideOpen||isC)?"8px 16px":"8px 0",margin:"1px 8px",borderRadius:8,background:a?C.sideActive:"transparent",cursor:"pointer",justifyContent:(sideOpen||isC)?"flex-start":"center"}} onMouseOver={e=>{if(!a)e.currentTarget.style.background=C.sideHover;}} onMouseOut={e=>{if(!a)e.currentTarget.style.background="transparent";}}>
          <I size={18} color={a?C.blue:C.text3}/>{(sideOpen||isC)&&<span style={{color:a?C.text:C.text2,fontSize:12,fontWeight:a?700:500}}>{item.label}</span>}</div>);})}</div>))}</div>
      {(sideOpen||isC)&&<div style={{borderTop:`1px solid ${C.border}`,padding:12}}><div style={{color:C.text3,fontSize:9,textAlign:"center"}}>v2.1</div></div>}</div>
    <div style={{flex:1,display:"flex",flexDirection:"column",minWidth:0}}>
      <div style={{background:C.bg2,borderBottom:`1px solid ${C.border}`,padding:`10px ${cp}px`,display:"flex",alignItems:"center",gap:12,flexShrink:0}}>
        <button onClick={()=>setSideOpen(!sideOpen)} style={{background:"none",border:"none",color:C.text2,cursor:"pointer",padding:4}}>{sideOpen&&!isC?<X size={18}/>:<Menu size={18}/>}</button>
        <span style={{color:C.text2,fontSize:12}}>{({home:"Overview",cnz_mapper:"CNZ Import Mapper",email_classifier:"Email Classifier",sku_checker:"SKU Checker"})[tab]||""}</span></div>
      <div style={{flex:1,overflow:"auto",padding:cp,display:"flex",justifyContent:"center"}}><div style={{width:"100%",maxWidth:mx}}>{renderContent()}</div></div></div>
  </div>);
}